data:
  _target_: find_my_bike.dataset.EbayDataModule
  dataset_path: /home/tilman/Programming/find-my-bike/data/ebay
  aspects: [bike, frame]
  batch_size: 64

model:
  _target_: find_my_bike.lightning.BikeClassifier
  encoder:
    _target_: find_my_bike.lightning.Encoder
    encoder:
      _target_: torchvision.models.resnet18
      pretrained: true
    output_node: avgpool
  head:
    _target_: find_my_bike.lightning.MultiAspectHead
    aspects: ???
    in_features: 512
  lr: 0.001
  encoder_lr_factor: 0.1

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 100
  log_every_n_steps: 1
  logger:
    _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: ./
    name: null
    version: ''
  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val/loss
      mode: min
    - _target_: pytorch_lightning.callbacks.early_stopping.EarlyStopping
      monitor: val/loss
      mode: min
      patience: 10
  plugins:
    _target_: find_my_bike.lightning.utils.TorchJitCheckpointIO